# Generated by Django 3.2.9 on 2021-11-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Squad Name')),
            ],
            options={
                'db_table': 'Squad',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Personal ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('user_estimated_hours', models.DurationField(blank=True, db_column='user_estimated_hours', help_text='Time in format: (HH:MM:SS)', null=True)),
                ('squadid', models.ForeignKey(db_column='squadid', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_squad', to='HoursApp.squad', verbose_name='Squad')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Title')),
                ('description', models.TextField()),
                ('spent_hours', models.DurationField(blank=True, db_column='spent_hours', help_text='Time in format: (HH:MM:SS)', null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to='HoursApp.user')),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
